### ISSUE TITLE
Add support to install this framework via Platformio library manager

### ISSUE THREAD

**Issue by garung1611** [rjwats/esp8266-react#191] opened 2020-08-21 08:36 UTC
Recently, I am finding a library for Wifi manager and Web OTA. I've tried quite a lot library and finaly I decide to use IotWebConf. But some days ago, I find out this framework. This framework is perfectly match my needs. It's the best framework when compare to other Wifi manager libraries. But because I cannot search this framework in library manager of PlatformIO (I use PlatformIO with VS Code). So, if you can add support to search and install this framework via Platformio library manager, I think many more people will know about it

**Comment by rjwats** [comment] 2020-08-21 08:45
Yes, It could be useful as a standalone WiFi manager for sure, although
it's pretty large compared to other libraries out there.

This had been the plan for a while and there's an issue already open for
using the framework as a library. I just haven't got around to it yet :)

https://github.com/rjwats/esp8266-react/issues/34

**Comment by rjwats** [comment] 2020-08-23 19:24
Yes, setData, unlike setState can't take a partial as it replaces the data
held by the RestComponent entirely. Your approach with the spread operator
is fine. I would have ordered it the other way around to avoid possible
errors when modifying this code in future like so:

{...rest, thing: "some value"}.

This way if "rest" contained a property named "thing", it would be
replaced, in this instance with "some value". On a side note, the component
RestComponent is a bit inflexible at times, it was intended to reduce code
duplication in the UI and does so at the expense of flexibility. I may
change this at some point.

There's nothing particularly wrong with your approach with mixing
state/settings there either, it's perfectly valid. Though as a matter of
preference I would have probably had two endpoints to keep it clear what
was state vs settings Only allowing POST on the settings endpoint. Though
with that approach, you have more endpoints of course - so pick your poison
:)

On "polling" vs "websockets", again, both will work. Personally I'd go with
polling unless there was a good reason to have it be event driven (i.e.
updating the client when something changes instead of on an interval
basis). There is a higher memory overhead for WebSockets and the client
code for polling is perfectly easy to implement, like you say, with
setInterval. Just be aware you'll need to hang on to the interval id and
remove it using clearInterval when the component unmounts.

Sounds like a fun project :)

**Comment by rjwats** [comment] 2020-08-23 19:24
Yes, setData, unlike setState can't take a partial as it replaces the data held by the RestComponent entirely. Your approach with the spread operator is fine. I would have ordered it the other way around to avoid possible errors when modifying this code in future like so:

`
{...rest, thing: "some value"}
`

This way if "rest" contained a property named "thing", it would be replaced, in this instance with "some value". On a side note, the component RestComponent is a bit inflexible at times, it was intended to reduce code duplication in the UI and does so at the expense of flexibility. I may change this at some point.

There's nothing particularly wrong with your approach with mixing state/settings there either, it's perfectly valid. Though as a matter of preference I would have probably had two endpoints to keep it clear what was state vs settings Only allowing POST on the settings endpoint. Though with that approach, you have more endpoints of course - so pick your poison :)

On "polling" vs "websockets", again, both will work. Personally I'd go with polling unless there was a good reason to have it be event driven (i.e. updating the client when something changes instead of on an interval basis). There is a higher memory overhead for WebSockets and the client code for polling is perfectly easy to implement, like you say, with setInterval. Just be aware you'll need to hang on to the interval id and remove it using clearInterval when the component unmounts.

Sounds like a fun project :)

**Comment by garung1611** [comment] 2020-08-24 08:23
Thanks rjwats so much. The "rest" approach sounds good. It's absolutely better than current. But  users need to call    **setData{...rest, thing: "some value"}**  or they just call **setData{thing: "some value"}** and the framework will do the rest?
 Your approach "two endpoints" is better than mine. It makes the code more clear and easy to read and maintenance. 
 About "polling" vs "websockets". I prefer the second approach _(use backend code to periodic send state variables to web socket connected clients)_ because follow reason:

- I'm using websocket method for transfering data between client and ESP because using this method, all the client can update when one client changed the state. So even don't need to periodic update the states, I still use this method because above benefit _(all the client can update when one client changed the state)_. And because i've alread used websocket so we can push back updated data to clients easily.

- With "polling" approach, I think it's pretty good with 1 client. But if two or more client connected, the requests to ESP will be double or more. I think, it will create more load for ESP. 

 I upload your example _(original version, not any changed)_ to my ESP8266 . I repeatedly switch on and off the LED and sometimes, ESP was automatically restarted. I don't know why. Is there anyway to see log, callstack or something else to investigate what make ESP restarted?

**Comment by rjwats** [comment] 2020-08-25 08:16
I have seen reset issues when using serial logging during WebSocket
callbacks on the ESP8266. If you open the serial terminal you can get the
trace which you can decode with:

https://github.com/me-no-dev/EspExceptionDecoder

Have you made any changes to the code, or are you seeing this issue when
using the code as is?

**Comment by garung1611** [comment] 2020-08-27 14:48
Yes, I'm using the code as is. But recently, everything seems to be fine. ESP8266 is not restarted anymore so I've not a chance to investigate why it was restarted in the past.
 rjwats, could you do me a favor? I want the guest user have rights to run scan networks and wifi settings in the Wifi Connection. I've digged into your framework, I removed "disabled" code as follow
![image](https://user-images.githubusercontent.com/69721339/91457358-77cb7f00-e8ae-11ea-9cb1-ae78a98fa87b.png)

With that modification, the tab "scan networks" and "wifi settings" will show when logged in by guest user but when I click to them, the framework redirect me to root page. Instead clicking there tabs, I type the address "http://localhost:3000/wifi/scan", it's still redirect me to root page. How could I grant guest to scan networks and wifi settings?

**Comment by rjwats** [comment] 2020-08-27 19:05
Have you changed the security predicate in the relevant places in the framework code?
The WiFiScanner and WiFiSettingsService use IS_ADMIN (which is the default for any http endpoint unless overridden):

https://github.com/rjwats/esp8266-react/blob/master/lib/framework/WiFiScanner.cpp
https://github.com/rjwats/esp8266-react/blob/master/lib/framework/WiFiSettingsService.cpp 

You can see how the demo project makes the endpoint accessible to all authenticated users by using the IS_AUTHENTICATED instead:

https://github.com/rjwats/esp8266-react/blob/master/src/LightStateService.cpp  

Hope this helps.

**Comment by garung1611** [comment] 2020-08-28 02:32
Thanks rjwats so much. Everything is fine now.

**Comment by garung1611** [comment] 2020-08-30 03:16
Thanks rjwats. With your framework and react, I can quickly create this app like that
![Screenshot_20200830-094318_Opera](https://user-images.githubusercontent.com/69721339/91650406-85992400-eaa9-11ea-8de7-c519a839c3d5.jpg)
![Screenshot_20200830-094154_Opera](https://user-images.githubusercontent.com/69721339/91650411-8f228c00-eaa9-11ea-8f07-9de74009cc03.jpg)
![Screenshot_20200830-093917_Opera](https://user-images.githubusercontent.com/69721339/91650417-96e23080-eaa9-11ea-9d40-21ed3e76e029.jpg)
![Screenshot_20200830-093907_Opera](https://user-images.githubusercontent.com/69721339/91650422-a06b9880-eaa9-11ea-8419-14596ff591b5.jpg)
![Screenshot_20200830-093858_Opera](https://user-images.githubusercontent.com/69721339/91650428-a82b3d00-eaa9-11ea-9f5d-6cc06a9d6cde.jpg)
![Screenshot_20200830-093853_Opera](https://user-images.githubusercontent.com/69721339/91650432-b11c0e80-eaa9-11ea-8e71-3e63d65b582c.jpg)
![Screenshot_20200830-093838_Opera](https://user-images.githubusercontent.com/69721339/91650433-b8dbb300-eaa9-11ea-9914-96aa8bc5cfb3.jpg)

**Comment by rjwats** [comment] 2020-08-30 09:48
Looking good, glad you could make use of it.

**Comment by garung1611** [comment] 2020-09-01 03:39
Dear rjwats!
 I've finished my small project using "websocket" method. Everything is fine as you seen via my screen capture above. Yesterday, I've tried the "polling" method according to your opinion. My code using "polling" method like follow:
![image](https://user-images.githubusercontent.com/69721339/91791973-a8a90c80-ec3e-11ea-81ac-5e5fab8e804a.png)


By this way, React UI can frequently update the states from ESP32, but it frequently redraw the component ControllerStateRestControllerForm so it make alitte bit flickering. By "websocket" method, there's no any flickering. "Websocket" method is like updating data using Ajax and "Polling" method is like updating data by refresh the screen. So, rjwats, the flickering issue is because I code wrong way or because the nature of "Polling" way?

> Yes, setData, unlike setState can't take a partial as it replaces the data held by the RestComponent entirely. Your approach with the spread operator is fine. I would have ordered it the other way around to avoid possible errors when modifying this code in future like so:
> 
> `{...rest, thing: "some value"}`
> 
> This way if "rest" contained a property named "thing", it would be replaced, in this instance with "some value". On a side note, the component RestComponent is a bit inflexible at times, it was intended to reduce code duplication in the UI and does so at the expense of flexibility. I may change this at some point.
> 
> There's nothing particularly wrong with your approach with mixing state/settings there either, it's perfectly valid. Though as a matter of preference I would have probably had two endpoints to keep it clear what was state vs settings Only allowing POST on the settings endpoint. Though with that approach, you have more endpoints of course - so pick your poison :)
> 
> On "polling" vs "websockets", again, both will work. Personally I'd go with polling unless there was a good reason to have it be event driven (i.e. updating the client when something changes instead of on an interval basis). There is a higher memory overhead for WebSockets and the client code for polling is perfectly easy to implement, like you say, with setInterval. Just be aware you'll need to hang on to the interval id and remove it using clearInterval when the component unmounts.
> 
> Sounds like a fun project :)

**Comment by rjwats** [comment] 2020-09-01 10:29
No, this is because loadData() sets the loading flag. The "flickering" you are seeing is the loading indicator being rendered during the HTTP request. A bit awkward, one of the reasons I'm no longer a fan of the RestController pattern I've implemented there. It's too restrictive.

If you added the following to the loadData function in RestController:

![image](https://user-images.githubusercontent.com/1330772/91838981-3fc59280-ec46-11ea-928a-f570ba6a6cc4.png)

You could call it with false to supress the loading indicator:

`loadData(false)`

**Comment by rjwats** [comment] 2020-09-01 10:35
I think the RestController pattern I've implemented is a bit restrictive at times. The loading indicator is why you are seeing flickering during the HTTP request. If you add the following to RestController.tsx you can supress the indicator:

![image](https://user-images.githubusercontent.com/1330772/91839390-e14ce400-ec46-11ea-9003-5a691fdafe15.png)

Now you can call loadData(false) to supress the indicator.

**Comment by garung1611** [comment] 2020-09-03 13:39
Dear rjwats, it did not work. after change the loadData function as you said, I've got this error.
![image](https://user-images.githubusercontent.com/69721339/92122220-61c93b80-ee25-11ea-9955-b60d711abaf4.png)
To bypass this error, I've change the code as follow.
![image](https://user-images.githubusercontent.com/69721339/92122340-80c7cd80-ee25-11ea-8d68-1ef2fe5589f3.png)
After that, no error occur but the screen is still flickering so I try another way by directly change the loading variable as follow
![image](https://user-images.githubusercontent.com/69721339/92122418-96d58e00-ee25-11ea-91a2-b5475d44b629.png)
With all above modifications, the screen is still flickering :(

**Comment by garung1611** [comment] 2020-09-04 14:44
Already changed as yours, everything works as intended. But in this way, i've to add arrow function ()=> to everywhere call to loadData. Instead this dirty way,I just change loadData in the interface from arrow function into any type, everything still works. Why you dont choose to change loadData to any type. It seems less dirty a little bit
![image](https://user-images.githubusercontent.com/69721339/92251821-9a394a00-eef7-11ea-8364-e1413ba59ebc.png)
![image](https://user-images.githubusercontent.com/69721339/92251853-a2918500-eef7-11ea-8fce-bf782a0ca4f4.png)

**Comment by rjwats** [comment] 2020-09-04 15:04
Using the "any" type is rarely the right thing to do in my experience. I only reserve it for utility functions which can operate defensively on literally "any" value being passed (_.isNull or _.isNumber are good examples) or possibly to provide compatibility with vanilla JavaScript.

In this situation, using "any" would mean you can now pass an object, number or string into the loadData prop. This would result in a runtime error when the callback is attempted, not to mention using "any" in this way defeats the purpose of using TypeScript.

Whilst it requires more code changes, it's definitely better practice to be stricter with the types in general. As loadData should be a function that takes a single, optional boolean argument it should be declared as such.

That being said - do as you wish :)

**Comment by rjwats** [comment] 2020-09-04 15:14
I also noted an error in my example which you may have already noticed, I wasn't calling the loadData function in my callbacks:

![image](https://user-images.githubusercontent.com/1330772/92255049-b1614300-eec9-11ea-97a9-f03c9069185a.png)

**Comment by garung1611** [comment] 2020-09-05 15:52
> Whilst it requires more code changes, it's definitely better practice to be stricter with the types in general. As loadData should be a function that takes a single, optional boolean argument it should be declared as such.
> 
Yes. I agree with you :)




> I also noted an error in my example which you may have already noticed, I wasn't calling the loadData function in my callbacks:
> 
> ![image](https://user-images.githubusercontent.com/1330772/92255049-b1614300-eec9-11ea-97a9-f03c9069185a.png)
 
On my machine, onClick={()=> this.props.loadData}> works fine. there is no any error.

**Comment by rjwats** [comment] 2020-12-22 13:04
Closing this now, please re-open if you need further help :)

**Closed by rjwats** 2020-12-22 13:04 UTC
